### ISSUE TITLE
ActiveTitle - HasFocus and TitleLocation is wrong

### ISSUE THREAD

**Issue by tuxuser** [joelday/DarkId.SmartGlass#12]
```
HasFocus - 1 bit
TitleLocation - remaining 15 bits
```

https://github.com/joelday/DarkId.SmartGlass/blob/c3ae08598c6a99db8657d7a2563aeca42fc580f0/src/DarkId.SmartGlass/ActiveTitle.cs#L19-L21

**Comment by tuxuser** [comment]
It's implemented correctly now

**Comment by joelday** [comment]
Ahh, forgot to close this one. Thanks.
