### ISSUE TITLE
Media control commands

### ISSUE THREAD

**Issue by zb140** [joelday/DarkId.SmartGlass#13]
Thanks for all the hard work on this; I've already successfully used it to integrate my Xbox into my home automation system, which I've been wanting to do for ages.

It works great, but I'd really like to go a little further.  Specifically, I'd like to implement the media control commands that become available when certain titles are playing video (pause, fast forward, etc.).  I've made a fair amount of progress simply by digging through disassembled code from the Win 10 Xbox app, to the point where I believe I've got almost everything I need to make it work.  Unfortunately, when it comes to actually sending the message over the network, the Windows app does a call into native code, making it impossible to confirm the exact details of the message format.  Also, crucially, although I can tell it's a session message very similar to the GamepadMessage, I have not yet found a way to determine what its SessionMessageType should be.

Can anyone help me shed some light on this?  I know the CLI tool has a Pcap command for decrypting network traces, and I know how to use Wireshark to capture network traffic, but the command requires a shared secret that I can't figure out how to get.  Any pointers in the right direction would be greatly appreciated!

**Comment by joelday** [comment]
@zb140 Glad you've been having fun with it! I believe all of the media playback control stuff is over Json, probably similarly to these requests made through the Smartglass "companion" API: http://sg.xboxlive.com/february2014-1/Xbc.js

**Comment by zb140** [comment]
@joelday Interesting, thanks for the pointer.  I'll play around with it and see what I can learn.

**Comment by tuxuser** [comment]
**Channel**: SystemMedia

# MediaState Message
__Message Type__: `0xF03`
__Response__: None
__Requests Ack__: `YES`

Informs client about media playback state

| Offset (hex) | Offset (dec) | Type        | Description
| ------------:| -----:| ------------------ | ---------------
| 0x00         |  0    | uint32             | Title Id
| 0x08         |  8    | SGString           | AUM Id
| 0x0A         | 10    | SGString           | Asset Id
| 0x0E         | 14    | uint16             | Media Type
| 0x12         | 18    | uint16             | Sound Level
| 0x16         | 22    | uint32             | Enabled commands
| 0x1A         | 26    | uint32             | Playback status
| 0x1E         | 30    | float32            | Rate
| 0x22         | 34    | uint64             | Position
| 0x2A         | 42    | uint64             | Media Start
| 0x32         | 50    | uint64             | Media End
| 0x38         | 58    | uint64             | Min Seek
| 0x42         | 66    | uint64             | Max Seek
| 0x4A         | 74    | uint16             | Metadata Length
| 0x4C         | 76    | MediaMetadata[len] | Metadata

__Title Id__: Title Id of media
__AUM Id__: Application User Model Id of media
__Asset Id__: Asset Id
__Media Type__: See [Media Type](#media-type)
__Sound Level__: See [Sound Level](#sound-level)
__Enabled commands__: See [Media Control Command](#media-control-command)
__Playback status__: See [Media Playback Status](#media-playback-status)
__Rate__: Playback rate
__Position__: Current media position (nanoseconds)
__Media Start__: Media start (nanoseconds)
__Media End__: Media end (nanoseconds)
__Min Seek__: Minimal seek position (nanoseconds)
__Max Seek__: Maximal seek position (nanoseconds)
__Metadata Length__: Length of Metadata array
__Metadata__: Array of [Media Metadata](#media-metadata)

## Sound Level

| Level                         | Value
| ----------------------------- | -------
| Muted                         | 0x00
| Low                           | 0x01
| Full                          | 0x02

## Media Playback Status

| Status                        | Value
| ----------------------------- | -------
| Closed                        | 0x00
| Changing                      | 0x01
| Stopped                       | 0x02
| Playing                       | 0x03
| Paused                        | 0x04

## Media Transport State

| State                         | Value
| ----------------------------- | -------
| Invalid                       | 0x00
| Stopped                       | 0x01
| Starting                      | 0x02
| Playing                       | 0x03
| Paused                        | 0x04
| Buffering                     | 0x05

## Media Type

| Type                          | Value
| ----------------------------- | -------
| NoMedia                    | 0x00
| Music                         | 0x01
| Video                         | 0x02
| Image                         | 0x03
| Conversation                  | 0x04
| Game                          | 0x05

## Media Metadata

| Offset (hex) | Offset (dec) | Type | Description
| ------------:| -----:| ----------- | ---------------
| 0x00         |  0    | SGString    | Name
| 0x??         |  ?    | SGString    | Value

# Media Command Message

__Message Type__: `0xF01`
__Response__: `None`
__Requests Ack__: `NO`

Sends media playback command to console

| Offset (hex) | Offset (dec) | Type | Description
| ------------:| -----:| ----------- | ---------------
| 0x00         |   0   | uint64      | Request Id
| 0x08         |   8   | uint32      | Title Id
| 0x0C         |  12   | uint32      | Command
| If Command == Seek
| 0x10         |  16   | uint32      | Seek position

__Request Id__: Request Id
__Title Id__: Title Id of media controller
__Command__: See [Media Control Command](#media-control-command)
__Seek position (optional)__: Only set if Command == Seek

## Media Control Command

| Flag              | Bits                  | Mask
| ----------------- | --------------------- | ------
| Play              | `0000 0000 0000 0010` | 0x02
| Pause             | `0000 0000 0000 0100` | 0x04
| Play Pause Toggle | `0000 0000 0000 1000` | 0x08
| Stop              | `0000 0000 0001 0000` | 0x10
| Record            | `0000 0000 0010 0000` | 0x20
| Next Track        | `0000 0000 0100 0000` | 0x40
| Previous Track    | `0000 0000 1000 0000` | 0x080
| Fast Forward      | `0000 0001 0000 0000` | 0x100
| Rewind            | `0000 0010 0000 0000` | 0x200
| Channel Up        | `0000 0100 0000 0000` | 0x400
| Channel Down      | `0000 1000 0000 0000` | 0x800
| Back              | `0001 0000 0000 0000` | 0x1000
| View              | `0010 0000 0000 0000` | 0x2000
| Menu              | `0100 0000 0000 0000` | 0x4000
| Seek              | `1000 0000 0000 0000` | 0x8000

**Comment by joelday** [comment]
@tuxuser Ohh yeah, derp. Thanks!

@zb140 Okay, so what you want to do is implement a channel for SystemMedia, similar to this: https://github.com/joelday/DarkId.SmartGlass/blob/master/src/DarkId.SmartGlass/Channels/InputChannel.cs, then create the various session messages that @tuxuser has awesomely provided. :)

**Comment by zb140** [comment]
I've submitted a pull request (#14) with what I came up with.  It includes the library code implementation as well as an update to the CLI to send media commands to the active app.  It's worked with every app I've tried it with so far.  I'd love to hear your comments!

@tuxuser Thanks for the excellent documentation.  If you're willing/able to share more, I'd also like to implement whatever messages get sent over the SystemInputTVRemote and SystemText channels.

**Comment by tuxuser** [comment]
@zb140 See #11

**Comment by tuxuser** [comment]
Can be closed

**Comment by chefbennyj1** [comment]
I realize this thread is closed but is there a code example for sending these commands.
