### ISSUE TITLE
Support for establishing game streaming sessions.

### ISSUE THREAD

**Issue by joelday** [joelday/DarkId.SmartGlass#3]
Configure and start a session and return connection info for the RTP stream.

**Comment by TylerD89** [comment]
This is needed... Slightly off topic, Why does Microsoft encrypt it in the first place? Every stream I start in Smartglass is ALWAYS laggy and the encryption they put in place does not help. Plus, its behind a freaking LAN!

**Comment by tuxuser** [comment]
@TylerD89 No cryptography is used while gamstreaming - only the initial connection to the console is secured.

**Comment by TylerD89** [comment]
Ahh... that makes more sense

**Comment by joelday** [comment]
Oh hey, this title is wrong. RTSP, right?

**Comment by tuxuser** [comment]
RTP it is ;)

**Comment by joelday** [comment]
I should do this. When life isn't derailing me constantly.

**Comment by joelday** [comment]
Done, currently just returns the session ports. Will be creating a new project that implements everything for the protocol on the Nano side next.

**Comment by joelday** [comment]
Oops.
